# Generated by Django 5.0.4 on 2024-09-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HBLTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="HBLManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hbl_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, null=True)),
                ("guid", models.CharField(default=None, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HBLPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.IntegerField(null=True)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("yahoo_player_key", models.CharField(max_length=20, null=True)),
                ("team_name", models.CharField(max_length=30, null=True)),
                (
                    "primary_position",
                    models.CharField(
                        choices=[
                            ("C", "Catcher"),
                            ("1B", "First Base"),
                            ("2B", "Second Base"),
                            ("3B", "Third Base"),
                            ("SS", "Shortstop"),
                            ("LF", "Left Field"),
                            ("CF", "Center Field"),
                            ("RF", "Right Field"),
                            ("Util", "Util"),
                            ("P", "Pitcher"),
                        ],
                        default="Util",
                        max_length=4,
                    ),
                ),
                (
                    "display_positions",
                    models.CharField(
                        default=models.CharField(
                            choices=[
                                ("C", "Catcher"),
                                ("1B", "First Base"),
                                ("2B", "Second Base"),
                                ("3B", "Third Base"),
                                ("SS", "Shortstop"),
                                ("LF", "Left Field"),
                                ("CF", "Center Field"),
                                ("RF", "Right Field"),
                                ("Util", "Util"),
                                ("P", "Pitcher"),
                            ],
                            default="Util",
                            max_length=4,
                        ),
                        max_length=20,
                    ),
                ),
                ("player_status", models.CharField(max_length=10, null=True)),
                ("keeper_cost_current", models.IntegerField(default=0)),
                ("keeper_cost_next", models.IntegerField(default=1)),
                ("seasons_on_team", models.IntegerField(default=0)),
                ("four_keeper_cost", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="HBLTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.IntegerField()),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ARGON_CONCLUSIONS", "AC"),
                            ("BOTTOM_OF_THE_LINEUP_CARD", "BotLC"),
                            ("CVILLE_STRANGERS", "CS"),
                            ("DIGITAL_SPACE_LOOP", "DSL"),
                            ("JAY_AND_BOBS_BOYS", "JBB"),
                            ("JIM_WOHLFORD_CLONES", "JWC"),
                            ("LITTLE_GIANTS_II", "LGII"),
                            ("MGS_WONDERBOYS", "MGWB"),
                            ("THE_STORAGE_JARS", "SJ"),
                            ("WABASH_GOATS", "WG"),
                        ],
                        max_length=25,
                    ),
                ),
                ("yahoo_team_key", models.CharField(max_length=20)),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team",
                        to="hbl.hblmanager",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HBLTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yahoo_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HBLAddPlayer",
            fields=[
                (
                    "hbltransaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hbl.hbltransaction",
                    ),
                ),
                ("yahoo_id", models.IntegerField()),
                ("waiver", models.BooleanField(default=False)),
            ],
            bases=("hbl.hbltransaction",),
        ),
        migrations.AddField(
            model_name="hbltransaction",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="hbl.hblplayer",
            ),
        ),
        migrations.AddField(
            model_name="hbltransaction",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="hbl.hblteam",
            ),
        ),
        migrations.CreateModel(
            name="HBLProspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("yahoo_player_key", models.CharField(max_length=20, null=True)),
                ("team_name", models.CharField(max_length=30, null=True)),
                (
                    "primary_position",
                    models.CharField(
                        choices=[
                            ("C", "Catcher"),
                            ("1B", "First Base"),
                            ("2B", "Second Base"),
                            ("3B", "Third Base"),
                            ("SS", "Shortstop"),
                            ("LF", "Left Field"),
                            ("CF", "Center Field"),
                            ("RF", "Right Field"),
                            ("Util", "Util"),
                            ("P", "Pitcher"),
                        ],
                        default="Util",
                        max_length=4,
                    ),
                ),
                ("player_status", models.CharField(max_length=10, null=True)),
                (
                    "hbl_team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prospects_team",
                        to="hbl.hblteam",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hblplayer",
            name="hbl_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team",
                to="hbl.hblteam",
            ),
        ),
        migrations.AddField(
            model_name="hblplayer",
            name="previous_hbl_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_team",
                to="hbl.hblteam",
            ),
        ),
        migrations.AddField(
            model_name="hbltransaction",
            name="trade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="hbl.hbltrade",
            ),
        ),
        migrations.CreateModel(
            name="HBLDropPlayer",
            fields=[
                (
                    "hbltransaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hbl.hbltransaction",
                    ),
                ),
                ("yahoo_id", models.IntegerField()),
                (
                    "add",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dropped_for",
                        to="hbl.hbladdplayer",
                    ),
                ),
            ],
            bases=("hbl.hbltransaction",),
        ),
    ]
