# Generated by Django 5.0.4 on 2024-09-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hbl", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hblmanager",
            name="hbl_id",
        ),
        migrations.RemoveField(
            model_name="hblplayer",
            name="player_id",
        ),
        migrations.RemoveField(
            model_name="hblteam",
            name="team_id",
        ),
    ]
