# Generated by Django 5.0.4 on 2024-09-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hbl", "0002_remove_hblmanager_hbl_id_remove_hblplayer_player_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hblteam",
            old_name="yahoo_team_key",
            new_name="yahoo_team_id",
        ),
    ]
