# Generated by Django 5.0.4 on 2024-09-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hbl", "0003_rename_yahoo_team_key_hblteam_yahoo_team_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hblplayer",
            old_name="yahoo_player_key",
            new_name="yahoo_player_id",
        ),
    ]
