# Generated by Django 5.0.4 on 2024-11-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hbl", "0005_remove_hbladdplayer_yahoo_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hblteam",
            name="name",
            field=models.CharField(
                choices=[
                    ("AC", "Argon Conclusions"),
                    ("BotLC", "Bottom of the Lineup Card"),
                    ("CS", "C-ville Strangers"),
                    ("DSL", "Digital Space Loop"),
                    ("JBB", "Jay and Bobs Boys"),
                    ("JWC", "Jim Wohlford Clones"),
                    ("LGII", "Little Giants II"),
                    ("MGWB", "MG's WonderBoys"),
                    ("SJ", "THE STORAGE JARS"),
                    ("WG", "Wabash Goats"),
                ],
                max_length=25,
            ),
        ),
    ]
