# Generated by Django 5.0.4 on 2024-11-24 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hbl", "0006_alter_hblteam_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hblplayer",
            name="hbl_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="hbl.hblteam",
            ),
        ),
        migrations.AlterField(
            model_name="hblplayer",
            name="previous_hbl_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_players",
                to="hbl.hblteam",
            ),
        ),
        migrations.AlterField(
            model_name="hblteam",
            name="manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager",
                to="hbl.hblmanager",
            ),
        ),
    ]
