# Generated by Django 5.0.4 on 2025-02-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hbl", "0008_alter_hblprospect_hbl_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hblplayer",
            name="display_positions",
            field=models.CharField(
                default=models.CharField(
                    choices=[
                        ("C", "Catcher"),
                        ("1B", "First Base"),
                        ("2B", "Second Base"),
                        ("3B", "Third Base"),
                        ("SS", "Shortstop"),
                        ("LF", "Left Field"),
                        ("CF", "Center Field"),
                        ("RF", "Right Field"),
                        ("Util", "Util"),
                        ("P", "Pitcher"),
                    ],
                    default="Util",
                    max_length=4,
                ),
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="hblplayer",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="hblplayer",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="hblplayer",
            name="yahoo_player_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="hblprospect",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="hblprospect",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="hblprospect",
            name="yahoo_player_key",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
